dynamic:
    event:
        output: active_ind
        length: 1
        always_included: true
        lookup: active_ind
    colourwayCode:
        output: memo3
        length: 10
        field_if_empty: OBJECTID
        always_included: true
    shortDescription:
        output: color_name
        length: 35
    abbreviation:
        output: color_name
        length: 35
    colorName:
        output: alt_name1
        length: 35
    longDescription:
        output: alt_name1
        length: 35
    colorType:
        output: memo2
        length: 35
        lookup: color_category
    status:
        output: status
        length: 8
        lookup: color_status
    RGB_R:
        output: rgb_r
        length: 3
    RGB_B:
        output: rgb_b
        length: 3
    RGB_G:
        output: rgb_g
        length: 3
    thumbnail:
        output: location
        length: 45
        is_attachment: true
static_defaults:
    owner: LULULEMON
