

com.lll.color.artwork.artWork=memo1|10-header
com.lll.color.artwork.artName=artwork_name|35-header
com.lll.color.artwork.colorType=artwork_type|8-header
com.lll.color.artwork.OBJECT_ID=combo_id|10-body
com.lll.color.artwork.abbreviation=combo_abrv|35-body
com.lll.color.artwork.colorName=combo_name|35-body
com.lll.color.artwork.status=status|8-body
com.lll.color.artwork.ground=memo3|10-detail
com.lll.color.artwork.color1=memo3|10-detail
com.lll.color.artwork.color2=memo3|10-detail
com.lll.color.artwork.color3=memo3|10-detail
com.lll.color.artwork.color4=memo3|10-detail
com.lll.color.artwork.color5=memo3|10-detail
com.lll.color.artwork.color6=memo3|10-detail
com.lll.color.artwork.color7=memo3|10-detail
com.lll.color.artwork.color8=memo3|10-detail
com.lll.color.artwork.color9=memo3|10-detail
com.lll.color.artwork.thumbnail=location|45-attachment
com.lll.color.artwork.default=owner:LULULEMON-header|attachment_no:IMAGE-attachment
com.lll.color.artwork.logical=header|artWork:memo1,body|artWork:memo1&OBJECT_ID:combo_id,detail|artWork:memo1&OBJECT_ID:combo_id

