
dynamic:
    event:
        output: active_ind
        length: 1
        always_included: true
        lookup: active_ind
    artwork:
        output: memo1
        length: 10
        always_included: true
        builder_list: lib_b,lib_h,lib_d
    artName:
        output: artwork_name
        length: 35
        builder_list: lib_h
    colorType:
        output: artwork_type
        length: 10
        builder_list: lib_h
    status:
        output: color_name
        length: 35
        builder_list: lib_h, lib_b
        lookup: color_status
    colorName:
        output: combo_name
        length: 35
        builder_list: lib_b
    abbreviation:
        output: combo_abrv
        length: 35
        builder_list: lib_b
    thumbnail:
        output: location
        length: 45
        is_attachment: true
        builder_list: lib_b
    ground:
        output: memo3
        length: 10
        builder_list: lib_d
    color1:
        output: memo3
        length: 10
        builder_list: lib_d
    color2:
        output: memo3
        length: 10
        builder_list: lib_d
    color3:
        output: memo3
        length: 10
        builder_list: lib_d
    color4:
        output: memo3
        length: 10
        builder_list: lib_d
    color5:
        output: memo3
        length: 10
        builder_list: lib_d
    color6:
        output: memo3
        length: 10
        builder_list: lib_d
    color7:
        output: memo3
        length: 10
        builder_list: lib_d
    color9:
        output: memo3
        length: 10
        builder_list: lib_d

static_defaults:
    owner: LULULEMON