swagger: '2.0'
info:
  title: Style Service
  description: This is the API for the Style entity and should be the way to parse style data.
  version: 0.0.1
schemes:
  - https
basePath: /v1
produces:
  - application/json
definitions:

# Bamboo Rose Response

# style
  styleBambooRoseResponse:
    type: object
    properties:
      document:
        $ref: '#/definitions/style_document'

  style_document:
    type: object
    properties:
      request:
        $ref: '#/definitions/request'

  request:
    type: object
    properties:
      quote:
        $ref: '#/definitions/quote'

  quote:
    type: object
    properties:
      "@owner":
        type: string
        description: "owner name"
      "@item_no":
        type: string
        description: "item number"
      "@description":
        type: string
        description: "description of item"
      "@season":
        type: string
        description: "Season"
      "@season_year":
        type: string
        description: "Season year"
      "@alt_desc1":
        type: string
        description: "alt_desc1"
      "@status_04":
        type: string
        description: "seasonal style type"
      "@request_type":
        type: string
        description: "request type"
      "@status_06":
        type: string
        description: "status"
      "@buy_program_no":
        type: string
        description: "buy program number"
      "@memo1":
        type: string
        description: "Design POD"
      "@brand":
        type: string
        description: "brand"
      "@class":
        type: string
        description: "class"
      "@subclass":
        type: string
        description: "sub class"
      "@dept":
        type: string
        description: "department"
      "@division":
        type: string
        description: "division"
      "@ref_no":
        type: string
        description: "What If Costing Group"
      "@subdept":
        type: string
        description: "Category"
      "@memo2":
        type: string
        description: "Design Line"
      "@status_01":
        type: string
        description: "Size Run Sample Status"
      "@status_03":
        type: string
        description: "Proto Sample Status"
      "@status_05":
        type: string
        description: "Calendar Track"
      "notes":
        $ref: '#/definitions/note'
      "size_ranges":
        $ref: '#/definitions/size_range'
      "quote_ext":
        $ref: '#/definitions/quote_ext'
      "attachment":
        $ref: '#/definitions/attachment'

  note:
    type: object
    properties:
      "@note_id":
        type: string
        description: "Note ID"
      "@text":
        type: string
        description: "Comments"

  size_range:
    type: object
    properties:
      "@size_range":
        type: string
        description: "size range"

  quote_ext:
    type: object
    properties:
      "@pattern_maker":
        type: string
        description: "pattern maker"
      "@prodmgr":
        type: string
        description: "prod manager"
      "@designer":
        type: string
        description: "designer"

  attachment:
    type: object
    properties:
      "@location":
        type: string
        description: "location"
      "@attachment_no":
        type: string
        description: "attachment number"
      "@custom_location":
        type: string
        description: "custom location"
      "@icon_location":
        type: string
        description: "icon location"
      "@largeview_location":
        type: string
        description: "largeview location"
      "@overview_location":
        type: string
        description: "overview location"
      "@thumbnail_location":
        type: string
        description: "thumbnail location"

# Color

  colorBambooRoseResponse:
    type: object
    properties:
      document:
        $ref: '#/definitions/color_document'

  color_document:
    type: object
    properties:
      "@xmlns:xsi":
        type: string
        description: "xlmns xsi"
      color_library:
        $ref: '#/definitions/color_library'

  color_library:
    type: object
    properties:
      colorlib_h:
        $ref: '#/definitions/colorlib_h'

  colorlib_h:
    type: object
    properties:
      "@memo3":
        type: string
        description: "Color No"
      "@color_name":
        type: string
        description: "Color Name"
      "@alt_name1":
        type: string
        description: "Alt Color Name"
      "@memo2":
        type: string
        description: "CATEGORY"
      "@status":
        type: string
        description: "Status"
      "@rgb_r":
        type: string
        description: "RGB_R"
      "@rgb_g":
        type: string
        description: "RGB_G"
      "@rgb_b":
        type: string
        description: "RGB_B"
      "@owner":
        type: string
        description: "owner"
      "@active_ind":
        type: string
        description: "Active"
      "attachment":
        $ref: '#/definitions/attachment'

# Artwork

  artworkBambooRoseResponse:
    type: object
    properties:
      document:
        $ref: '#/definitions/artwork_document'

  artwork_document:
    type: object
    properties:
      artwork_lib:
        $ref: '#/definitions/artwork_lib'

  artwork_lib:
    type: object
    properties:
      artwork_lib_h:
        $ref: '#/definitions/artwork_lib_h'

  artwork_lib_h:
    type: object
    properties:
      "@artwork_name":
        type: string
        description: "Artwork Name"
      "@owner":
        type: string
        description: "owner"
      "@active_ind":
        type: string
        description: "active indicator"
      "@memo1":
        type: string
        description: "Artwork Reference Object ID"
      "@artwork_type":
        type: string
        description: "Artwork Type"
      "@status":
        type: string
        description: "status"
      artwork_lib_b:
        $ref: '#/definitions/artwork_lib_b'

  artwork_lib_b:
    type: object
    properties:
      "@combo_id":
        type: string
        description: "Combo ID"
      "@memo1":
        type: string
        description: "Artwork No"
      "@combo_name":
        type: string
        description: "Combo Name"
      "@combo_abrv":
        type: string
        description: "Combo"
      "@status":
        type: string
        description: "status"
      artwork_lib_d:
        type: array
        items:
          $ref: '#/definitions/artwork_lib_d'
      "attachment":
        $ref: '#/definitions/attachment'

  artwork_lib_d:
    type: object
    properties:
      "@memo3":
        type: string
        description: "Color ID"
      "@color_pos":
        type: string
        description: "Color Position"
      "@memo1":
        type: string
        description: "Artwork No"
      "@combo_id":
        type: string
        description: "Combo ID"

# IF11

  if11BambooRoseResponse:
    type: object
    properties:
      document:
        $ref: '#/definitions/if11_document'

  if11_document:
    type: object
    properties:
      request:
        $ref: '#/definitions/if11_request'

  if11_request:
    type: object
    properties:
      "quote":
        type: array
        items:
          $ref: '#/definitions/if11_quote'

  if11_quote:
    type: object
    properties:
      "@season":
        type: string
        description: "Season"
      "@item_no":
        type: string
        description: "Item Number"
      "@Fowner":
        type: string
        description: "owner"
      "sell_channel":
        type: array
        items:
          $ref: '#/definitions/if11_sell_channel'

  if11_sell_channel:
    type: object
    properties:
      "@selling_channel":
        type: string
        description: "Selling Channel"
      "@plan_total":
        type: string
        description: "Plan Total"
      "sell_channel_flow":
        $ref: '#/definitions/if11_sell_channel_flow'

  if11_sell_channel_flow:
    type: object
    properties:
      "@plan_id":
        type: string
        description: "Plan ID"
      "@plan_qty":
        type: string
        description: "Plan Quantity"
      "sell_channel_d":
        $ref: '#/definitions/if11_sell_channel_d'
      "sell_channel_defn":
        type: array
        items:
          $ref: '#/definitions/if11_sell_channel_definition'

  if11_sell_channel_d:
    type: object
    properties:
      "@alloc_by_1":
        type: string
        description: "STORE"
      "@alloc_by_2":
        type: string
        description: "Plan ID"
      "@alloc_by_3":
        type: string
        description: "STYC"

  if11_sell_channel_definition:
    type: object
    properties:
      "@attrib_value":
        type: string
        description: "Attribute Value"
      "@attrib_name":
        type: string
        description: "Attribute Name"

# FlexPLM Input

# style

  styleFlexPLMResponse:
    type: object
    properties:
      Flex_interface:
        $ref: '#/definitions/flex_interface'

  flex_interface:
    type: object
    properties:
      FlexPLM_Header:
        $ref: '#/definitions/flexplm_header'

  flexplm_header:
    type: object
    properties:
      EVENT:
        type: string
        description: "event type"
      INTERFACE:
        type: string
        description: "interface name"
      TIMESTAMP:
        type: string
        description: "A UTC timestamp for when the response was given"
      Transaction_ID:
        type: string
        description: "A transaction ID generated by FlexPLM"
      Attribute_List:
        type: array
        items:
          $ref: '#/definitions/attribute'

  attribute:
    type: object
    properties:
      OBJECT_LEVEL:
        type: string
        description: "object level"
      OBJECT_ID:
        type: string
        description: "object id"
      FLEXTYPE:
        type: string
        description: "flex type"
      FIELD_NAME_KEY:
        type: string
        description: "field name key"
      FIELD_NAME_DISPLAY:
        type: string
        description: "field name display"
      FIELD_VALUE_KEY:
        type: string
        description: "field name value"
      FIELD_VALUE_DISPLAY:
        type: string
        description: "field name display"
      FIELD_TYPE:
        type: string
        description: "field type"
      CHANGE_IND:
        type: string
        description: "change indicator"

## Color

  colorFlexPLMResponse:
    type: object
    properties:
      Flex_interface:
        $ref: '#/definitions/flex_interface'

## Artwork

  artworkFlexPLMResponse:
    type: object
    properties:
      Flex_interface:
        $ref: '#/definitions/flex_interface'

## IF 11 RPAS to BR

# Rules

  mapping_config:
    type: object
    properties:
      mapping_rules:
          $ref: '#/definitions/mapping_rule'

  mapping_rule:
    type: object
    properties:
      active_ind:
        type: array
        items:
          $ref: '#/definitions/flex_br_mapping'
      color_status:
        type: array
        items:
          $ref: '#/definitions/flex_br_mapping'
      color_category:
        type: array
        items:
          $ref: '#/definitions/flex_br_mapping'
      quote_seasonal_type:
        type: array
        items:
          $ref: '#/definitions/flex_br_mapping'
      quote_season_style_level_status:
        type: array
        items:
          $ref: '#/definitions/flex_br_mapping'
      quote_season_style_option_level_status:
        type: array
        items:
          $ref: '#/definitions/flex_br_mapping'
      quote_category:
        type: array
        items:
          $ref: '#/definitions/flex_br_mapping'
      quote_design_line:
        type: array
        items:
          $ref: '#/definitions/flex_br_mapping'
      quote_calendar_track:
        type: array
        items:
          $ref: '#/definitions/flex_br_mapping'
      quote_proto_sample_status:
        type: array
        items:
          $ref: '#/definitions/flex_br_mapping'
      quote_size_run_sample_status:
        type: array
        items:
          $ref: '#/definitions/flex_br_mapping'
      quote_design_pod:
        type: array
        items:
          $ref: '#/definitions/flex_br_mapping'

  flex_br_mapping:
    type: object
    properties:
      flex_code:
        type: string
        description: "FlexPLM code"
      br_code:
        type: string
        description: "Bamboo Rose code"